### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by jozefizso** [chrisoldwood/vdproj2wix#1]
Please, add information about the license for the source code.

**Comment by chrisoldwood** [comment]
It's already in the manual (`HelpFile\vdproj2wix.html`):

```
License & Warranty
This script is freeware - you get what you pay for, nothing more, nothing less.
```

**Comment by chrisoldwood** [comment]
I'm currently in the process of adding the following MIT license to my home page, GitHub repos and documentation, so please consider this link as a formal license in the meantime:

http://www.chrisoldwood.com/LICENSE.txt

**Comment by chrisoldwood** [comment]
MIT license formally added. It's only taken 2 years 🙂.
