### ISSUE TITLE
$wixFile should be used instead of $file in line 313

### ISSUE THREAD

**Issue by banoz** [chrisoldwood/vdproj2wix#2]
https://github.com/chrisoldwood/vdproj2wix/blob/8657df8558cbbde086c530e6826b8cc49ac8afe1/vdproj2wix.ps1#L313

**Comment by chrisoldwood** [comment]
Thank you for pointing this out!

I think there is something more fundamentally wrong with `writeFileSystemTree` though as `$file` is initially used as a parameter for the output file but then on line 334 it's used as the name of a loop variable! I suspect the reason I ended up switching to using `$wixFile` mid function for the output file is probably to fix the shadowing of `$file`. Hence I think the real answer is to rename the final parameter and use it consistently and stop mixing-and-matching.
